Adding mypy
G-Research/armada pull request #1267
Opened 2022-07-25 19:08 UTC by Sharpz7

Closes https://github.com/G-Research/armada/issues/1236

2022-07-25 19:28 UTC, kannon92 requested changes
LGTM!  I asked Adam to go ahead and add these toolchain to the airflow operator also.

2022-07-25 19:53 UTC, kannon92 commented on third_party/airflow/tox.ini
> +    mypy --exclude '^(.*_pb2.*\.py$|.*_pb2.*\.pyi$|.*typings.py)$' --ignore-missing-imports armada/operators tests/ examples/
```suggestion
    mypy --exclude '^(.*_pb2.*\.py$|.*_pb2.*\.pyi$' --ignore-missing-imports armada/operators tests/ examples/
```

We don't have typings for airflow operator.

2022-07-25 19:53 UTC, kannon92 commented on third_party/airflow/tox.ini
> +    mypy --exclude '^(.*_pb2.*\.py$|.*_pb2.*\.pyi$|.*typings.py)$' --ignore-missing-imports armada/operators tests/ examples/
```suggestion
    mypy --exclude '^(.*_pb2.*\.py$|.*_pb2.*\.pyi$' --ignore-missing-imports armada/operators tests/ examples/
```

Same.

2022-07-26 14:04 UTC, kannon92 approved these changes

2022-07-26 19:21 UTC, jayofdoom approved these changes

2022-07-26 20:40 UTC, merged