Docs/quickstart improvement
G-Research/armada pull request #1366
Opened 2022-08-10 17:55 UTC by dans77777

![Screenshot (152)](https://user-images.githubusercontent.com/61909995/183982869-0ac7a198-6827-4357-90c4-4d5bbbe42094.png)
adding screenshot of the formatted links and text

2022-08-10 21:47 UTC, jayofdoom requested changes
These changes mostly look good, but are just targeted to the wrong place. If you re-target this to master branch, docs/ folder, we'll be able to review it in more detail.

2022-08-10 21:47 UTC, jayofdoom commented on python_airflow_operator.md
> +### _class_ armada.operators.armada.ArmadaOperator(name, armada_client, job_service_client, queue, job_request_items, \*\*kwargs)
This file is automatically generated and should not be manually changed.

2022-08-10 21:47 UTC, jayofdoom commented on developer.md
> +* Golang >= 1.18 installed [https://golang.org/doc/install](https://golang.org/doc/install)
Hey, these are good updates, but we do something strange for some of these files. They are copied over from docs/*.md on commit to the master branch. So for the changes to developer.md, quickstart.md, and libraries.md, lets put them in the versions here https://github.com/G-Research/armada/tree/master/docs and automation will pull them over. (So you'll need a new PR, off master branch and targeted at master branch).

2022-08-11 06:13 UTC, closed without merging

2022-08-11 06:13 UTC, dans77777 commented
closing the pull request as it has too much mess. will raise new one with all of the changes required