Contributing docs improvement
G-Research/armada pull request #1387
Opened 2022-08-16 12:15 UTC by dans77777

fixes #1302

2022-08-17 14:36 UTC, kannon92 commented on CONTRIBUTING.md
> +setup everything you’ll need to get started running and developing Armada:
```suggestion
Setup everything you’ll need to get started running and developing Armada:
```

2022-08-17 14:37 UTC, kannon92 requested changes
small suggestion you can apply but LGTM overal

2022-08-22 07:04 UTC, dans77777 commented on CONTRIBUTING.md
> +setup everything you’ll need to get started running and developing Armada:
changes are done. pls check once. @kannon92

2022-08-22 10:53 UTC, kannon92 approved these changes

2022-08-22 15:09 UTC, jayofdoom approved these changes
My comment can be addressed in this PR or in a follow up, but we should make sure those existing docs get linked into here at some point.

2022-08-22 15:09 UTC, jayofdoom commented on CONTRIBUTING.md
> +To work with [Armada website](https://armadaproject.io/), please checkout this branch:
This isn't universally true, for some docs, they need to be updated in master branch (such as this one). I'd suggest linking directly to https://github.com/G-Research/armada/blob/gh-pages/README.txt and https://github.com/G-Research/armada/blob/master/docs/docs-readme.md to help explain the relationship.

2022-08-22 15:17 UTC, merged