issue #1435 -- use 160 column line length lint and correct violations
G-Research/armada pull request #1437
Opened 2022-08-30 19:11 UTC by suprjinx

2022-08-30 20:50 UTC, kannon92 reviewed
Hey Geoffrey!  Thanks for your first PR!  This looks good to me.  I will make sure tests pass before giving final approval!

2022-08-31 15:55 UTC, kannon92 requested changes

2022-08-31 15:58 UTC, suprjinx commented on internal/pulsarutils/async.go
> +// consumerId: Internal Id of the consumer.  We use this so that when messages from different consumers are
hmm yeah where'd that second line go... fixing

2022-08-31 16:00 UTC, suprjinx commented on .golangci.yml
> +    - pkg/api
okay i'll narrow this -- I wonder if it's worth isolating the generated code better?

2022-08-31 16:24 UTC, suprjinx commented on internal/pulsarutils/async.go
> +// consumerId: Internal Id of the consumer.  We use this so that when messages from different consumers are
this file still looks correct on the branch, so something is funky with the diff:

https://github.com/suprjinx/armada/blob/line-length-lint/internal/pulsarutils/async.go

2022-08-31 16:41 UTC, suprjinx commented on .golangci.yml
> +    - pkg/api
just removed -- golangci passes locally without it so we'll see how CI does

2022-08-31 17:21 UTC, kannon92 commented on .golangci.yml
> +    - pkg/api
Yea I think that is a good idea for a follow up.

2022-08-31 18:27 UTC, suprjinx commented on .golangci.yml
> +    - pkg/api
The docs say that golangci-lint detects and skips autogen files, so I think we can just leave the config as is

2022-08-31 18:58 UTC, kannon92 approved these changes

2022-08-31 21:47 UTC, richscott approved these changes
Much easier on the eyes!

2022-08-31 21:54 UTC, jayofdoom approved these changes

2022-08-31 22:00 UTC, merged