armada-load-tester loadtest not submitting without --watch fix
G-Research/armada pull request #428
Opened 2020-09-10 14:45 UTC by carlocamurri

fix #419 

Use a nested WaitGroup to ensure level 1 goroutines wait for level 2 goroutines.

Can alternatively be done using same WaitGroup and expecting two routines to finish (`Add(2)`), as there is a 1-1 mapping between level 1 and level 2 goroutines. Thought this way was more explicit.

2020-09-10 15:20 UTC, jankaspar requested changes
Looks alright, just small naming change.

2020-09-10 15:20 UTC, jankaspar commented on pkg/client/load-test.go
> +				nestedWg := &sync.WaitGroup{}
I would name this according to what it is for i.e `submissionWg`, `jobSubmissionWg`, or something like that.

2020-09-10 15:22 UTC, JamesMurkin commented
You could even have runSubmission function create the waitGroup and return it. Call it something like submissionComplete.

Then callers to runSubmission can use the waitGroup to wait for submission to finish.

2020-09-10 15:30 UTC, carlocamurri commented
Thanks for the comments, will proceed to fix

2020-09-10 17:15 UTC, JamesMurkin approved these changes

2020-09-11 08:22 UTC, jankaspar approved these changes

2020-09-11 14:03 UTC, merged