Lookout UI Job Cancellation
G-Research/armada pull request #477
Opened 2020-12-15 16:20 UTC by carlocamurri

Allows users to cancel jobs from the Lookout UI.

Note that this requires CORS to be enabled on the Armada API.

![image](https://user-images.githubusercontent.com/14963658/102241114-83d85c80-3ef0-11eb-8f0e-183c1ef3a446.png)

![image](https://user-images.githubusercontent.com/14963658/102241899-6657c280-3ef1-11eb-8e39-f990ce2bfd1e.png)

2020-12-16 11:01 UTC, jankaspar requested changes
Looks alright except the CORS policy.

2020-12-17 08:27 UTC, devlounge commented on internal/common/grpc/gateway.go
> +func allowCORS(h http.Handler) http.Handler {
I think that this cancellation popup contains too much the word "cancel"

Cancel Jobs
Cancel the following jobs
CANCEL JOBS

2020-12-17 08:27 UTC, devlounge commented
I think that this cancellation popup contains too much the word "cancel"

Cancel Jobs
Cancel the following jobs
CANCEL JOBS

2020-12-17 15:26 UTC, jankaspar commented on config/armada/config.yaml
> +corsAllowedOrigins: ["http://localhost:3000"]
I would prefer default to be empty and set inside helm chart to lookout domain. It is minor but we don't want any localhost to talk to the api.

2020-12-18 11:14 UTC, jankaspar approved these changes

2020-12-18 12:26 UTC, merged