[issue-784] Lower the container validation restrictions for limits and request
G-Research/armada pull request #834
Opened 2021-12-16 12:10 UTC by steffnova

[Problem]

Issue is described here: #784

[Solution]

In order to comply with the way kubernetes works following scenarios need to be covered:
  - providing limits, but no requests in container specification
  - providing request, bot no limits in continer specification
  - providing limits and request in continer specification

Missing both of them will still cause an error (which has been updated)

Close #784

2021-12-17 12:10 UTC, severinson requested changes

2021-12-17 15:54 UTC, steffnova commented on internal/common/validation/podspec.go
> +			return fmt.Errorf("container %v has no resource request or limits specified", container.Name)
@severinson thanks for taking time to review.

These changes have been reverted and are outdated.

2021-12-17 15:55 UTC, steffnova commented on internal/common/validation/podspec.go
>  	return validatePorts(spec)
These changes are also outdated.

2021-12-20 11:01 UTC, severinson commented
What's the status of this PR? Should it be re-reviewed?

2021-12-24 13:23 UTC, robertdavidsmith approved these changes

2021-12-24 14:32 UTC, merged